In [ ]:
import pandas as pd
import numpy as np

tags_df = pd.read_csv("tag_rows.csv")
poi_df = pd.read_csv("poi_rows.csv")
poi_tags_df = pd.read_csv("poi_tag_rows.csv")
user_preferences_df = pd.read_csv("user_surprise_me_preferences_rows.csv")



   id                                             name  \
0   1                       National Gallery Singapore   
2   3  Sri Mariamman Temple: Hindu Temple in Singapore   
3   4                     Armenian Church in Singapore   
4   5                                CHIJMES Singapore   
9  10             Chinatown Heritage Centre, Singapore   

                                         description  latitude   longitude  \
0  Take in the region’s newest and largest muse...     1.290  103.851356   
2  Located in Chinatown, the Sri Mariamman Temple...     1.282  103.845380   
3  The oldest Christian church in Singapore is an...     1.293  103.849660   
4  Whether functioning as a school or a lifestyle...     1.295  103.851680   
9  Experience how Singapore’s early Chinese mig...     1.284  103.844350   

                      created_at  \
0  2025-10-02 09:08:56.805071+00   
2  2025-10-02 09:08:56.805071+00   
3  2025-10-02 09:08:56.805071+00   
4  2025-10-02 09:08:56.805071+00   
9 

In [ ]:
tag_indexes = {}
for index, row in tags_df.iterrows():
    tag_indexes[row['id']] = index

poi_indexes = {}
for index, row in poi_df.iterrows():
    poi_indexes[row['id']] = index

print(tag_indexes)
print(poi_indexes)



{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19}
{1: 0, 3: 2, 4: 3, 5: 4, 10: 9, 11: 10, 12: 11, 14: 13, 15: 14, 16: 15, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 25: 24, 28: 27, 29: 28, 30: 29, 34: 33, 35: 34, 36: 35, 37: 36, 38: 37, 39: 38, 40: 39, 41: 40, 42: 41, 43: 42, 45: 44, 47: 46, 48: 47, 51: 50, 52: 51, 53: 52, 54: 53, 55: 54, 56: 55, 57: 56, 58: 57, 61: 60, 65: 64, 66: 65, 68: 67, 72: 71, 74: 73, 75: 74, 76: 75, 78: 77, 79: 78, 82: 81, 85: 84, 87: 86, 88: 87, 89: 88, 90: 89, 91: 90, 93: 92, 94: 93, 95: 94, 99: 98, 100: 99, 101: 100, 103: 102, 104: 103, 107: 106}


In [63]:
# Create poi tag matrix. [tag_index, poi_index] = 1 if poi has tag, 0 otherwise
poi_tag_matrix = np.zeros((len(tags_df), len(poi_df)))
print(poi_tag_matrix.shape)

for index, row in poi_tags_df.iterrows():
    poi_id = row['poi_id']
    poi_index = poi_indexes.get(poi_id)
    if poi_index is None:
        continue
    tag_index = tag_indexes[row['tag_id']]
    poi_tag_matrix[tag_index, poi_index] = 1

# print(poi_tag_matrix)
print(poi_tag_matrix.shape)



(20, 66)


IndexError: index 67 is out of bounds for axis 1 with size 66

In [ ]:
number_of_poi_reviews = np.zeros((len(poi_df), 1))

# For simplicity, we treat a count of a review as the number of occurrences in
# user_preferences_df.
for index, row in user_preferences_df.iterrows():
    poi_index = poi_indexes[row['poi_id']]
    number_of_poi_reviews[poi_index] += 1

print(number_of_poi_reviews.shape)
print(number_of_poi_reviews)


(550, 1)
[[1.]
 [0.]
 [1.]
 [1.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [2.]
 [1.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [2.]
 [1.]
 [0.]
 [1.]
 [2.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 

In [ ]:
likes_count = np.zeros((len(poi_df), 1))

for index, row in user_preferences_df.iterrows():
    poi_index = poi_indexes[row['poi_id']]
    likes_count[poi_index] += 1

likes_proportion = np.zeros((len(poi_df), 1))

for index, row in poi_df.iterrows():
    poi_index = poi_indexes[row['id']]
    if number_of_poi_reviews[poi_index] == 0:
        likes_proportion[poi_index] = 0
    else:
        likes_proportion[poi_index] = likes_count[poi_index] / number_of_poi_reviews[poi_index]

print(likes_proportion.shape)
print(likes_proportion)


(550, 1)
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 

In [ ]:
# user_preferences_vector is a vector of user preferences.
# must be of size 1 x len(tags_df)
def f_preferences(user_preferences_vector, poi_tag_matrix):
    # user_preferences_vector is a vector of size 1 x len(tags_df)
    preference_scores = user_preferences_vector @ poi_tag_matrix
    # Transpose it. We want a vector of size len(poi_df) x 1
    preference_scores = preference_scores.T
    return preference_scores

# Simple test
user_preferences_vector = np.random.rand(1, len(tags_df))
res = f_preferences(user_preferences_vector, poi_tag_matrix)
print(res.shape)


(550, 1)


In [ ]:
# number_of_poi_reviews is a vector of size 1 x len(poi_df)
def f_poi_reviews(number_of_poi_reviews):
   # For each poi, we do a log2(number_of_reviews + 1) / log2(max_number_of_reviews + 1)
   # We use log to avoid domination by outliers.
   max_number_of_reviews = np.max(number_of_poi_reviews)
   return np.log2(number_of_poi_reviews + 1) / np.log2(max_number_of_reviews + 1)

# Simple test
# number_of_poi_reviews = np.random.randint(0, 100, (len(poi_df), 1))

res = f_poi_reviews(number_of_poi_reviews)
print(res.shape)
print(res)

(550, 1)
[[0.63092975]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [1.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.        ]
 [1.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [1.        ]
 [1.        ]
 [1.        ]
 [0.63092975]
 [1.        ]
 [0.63092975]
 [0.        ]
 [0.63092975]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.63092975]
 [1.        ]
 [0.63092975]
 [0.63092975]
 [1.        ]
 [0.63092975]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.63092975]
 [0.63092975]
 [0.        ]
 [0.63092975]
 [0.        ]
 [0.        ]
 [0.       

In [ ]:
def f_poi_likes_proportion(poi_likes_proportion):
    # poi_likes_proportion is a vector of size 1 x len(poi_df)
    # Same as the input.
    return poi_likes_proportion